CREATE USER 'bamboohub'@'%' IDENTIFIED BY '7777';

GRANT ALL PRIVILEGES ON *.* TO 'bamboohub'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS bamboohub;
USE bamboohub;

SET FOREIGN_KEY_CHECKS=0;