services:
  bamboohub:
    image: container-registry.oracle.com/mysql/community-server:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '7777'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - bamboohub-data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  bamboohub-data: